module.exports = {
    'GET wallet': ['wallet', false],
    'GET wallet/address': ['wallet/address', true],
    'GET wallet/addresses': ['wallet/addresses', false],
    'GET wallet/seeds': ['wallet/seeds', false],
    'GET wallet/seedaddrs': ['wallet/seedaddrs', false],
    'GET wallet/transactions': ['wallet/transactions', false],
    'GET wallet/backup': ['wallet/backup?destination=/home/wallet-settings.backup', true],
    'GET wallet/verifypassword': ['wallet/verifypassword?password=', true],
    'GET wallet/watch': ['wallet/watch', true],
    'POST wallet/lock': ['wallet/lock', false, false, true],
    'POST wallet/unlock': ['wallet/unlock', true, true],
    'GET consensus': ['consensus', false],
    'GET consensus/blocks': ['consensus/blocks', false],
    'GET skynet/portals': ['skynet/portals', false],
    'POST skynet/portals': ['skynet/portals', true, false, true],
    'GET skynet/skylink': ['skynet/skylink', false],
    'GET gateway': ['gateway', false],
    'GET daemon/alerts': ['daemon/alerts', false],
    'GET daemon/constants': ['daemon/constants', true],
    'GET daemon/settings': ['daemon/settings', true],
    'GET daemon/stop': ['daemon/stop', true],
    'GET daemon/update': ['daemon/update', true],
    'GET daemon/version': ['daemon/version', true]
}